### PR TITLE
remove rest tests to external service

### PR DESCRIPTION
**Pull request by ivy-lli**

### CODE REVIEW

**Comment by ivy-rew** [comment]
What did you solve with this? do we have a replacement infrastructure? do we have a mock service? What should customers user instead? What will we do to test our REST stack?

**Comment by ivy-lli** [comment]
Those are calls to external services and if those services are slow the build is failing. I think this can not be the solution and it's very annoying as scrum master, especially if this failure is in an rcptt which is not so understandable.
And yes today we have other possibilities to test something like that. (there is already a WebTest for simple rest calls, but this one don't test this external service too, because of the same reasons above). Maybe we should add a new Process test...

**Comment by ivy-rew** [comment]
If timeouts are the issue, did we try to raise them on the rest client itself? It's just very sad to loose all these nice high level integration tests.

**Comment by ivy-ohe** [comment]
I personally don't really understand why we use UI tests to check the availability of those services, or am I missing something? Was it out of convenience?

Alternatively we could enhance the *assertRuntimeLogMsg* method with some sort of try-cach mechanism that for example runs a max amount of 10 times and waits 5 seconds each execution. This would give the service max 50 seconds to respond.

**Comment by ivy-rew** [comment]
we did not have any BPM tests that could guarantee that the shown demos actually work. 
so they do not exist to assert runtime logs ... but to verify that the demo works .. .and yes, that the used services are still up and running. So if we have an issue with these services, we should focus on that ... 

Today we should write such tests using @IvyProcessTest ... which is not possible on 8.0 and maybe never will be. But we should do that for 'master'

However, deleting Tests lighthearted is not what we should opt for without thoughtful consideration impact.

**Pull request merged**
